FROM golang:1.13.4

ENV VERSION v1.0.29
ENV GOCACHE /tmp
WORKDIR /go/src/github.com/oleksiihead/films-parser/films-parser

RUN wget https://github.com/sonatype-nexus-community/nancy/releases/download/$VERSION/nancy-$VERSION-linux-amd64 -O nancy && \
    chmod +x nancy && mv nancy /usr/local/bin/nancy
RUN go get -u golang.org/x/lint/golint

COPY . .

RUN dep init

RUN go get -v
